version: "3"
services:
  btcwrapp:
    build: .
    depends_on:
      - bitcoin-service
    networks:
      - test-network
    environment:
      - RPC_USER
      - RPC_PASSWORD
    command: ["bash", "/project/docker/run_tests.sh"]
  bitcoin-service:
    image: "rotwatsb/bitcoin-service:latest"
    networks:
      - test-network
    ports:
      - "8333:8333"
    environment:
      - RPC_USER
      - RPC_PASSWORD
      - RPC_CLIENT_HOST
    volumes:
      - bitcoindata:/data
volumes:
  bitcoindata:
networks:
  test-network:
    driver: bridge
